name: adaptive_shimmer
description: "A lightweight, zero-dependency skeleton loader with shimmer and pulse animations, screen-wide shimmer, exclude widgets, and shape-adaptive capabilities."
version: 1.0.0
homepage: https://github.com/abhijithsabudev/adaptive_shimmer
repository: https://github.com/abhijithsabudev/adaptive_shimmer

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
